name: .NET

on:
  push:
    branches: 
      - 'main'
    tags:        
      - '*'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RedisHost: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Test
        run: make test
      - name: execute console to see if it runs
        run: make start
  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      RedisHost: localhost
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Publish console apps
        run: make publish
      - name: Build Docker image
        run: make docker-build
      - name: Push images
        run: make #docker-login docker-push
      
